name: Build 🛠

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: [main, develop] }

jobs:
  tests:
    name: ${{ matrix.targetPlatform }} 🚀
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Build-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-Build-
            Library-
      - run: touch test.artifact.file
      - uses: game-ci/unity-builder@14b33954b53f4fb42446c726c9b0d78b3fc1bb1f
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build (${{ matrix.targetPlatform }})
          path: build/${{ matrix.targetPlatform }}
